---
# We need sudo for some of the Docker commands.
sudo: required

services:
  - docker

env:
  # Odoo version for the test
  - ODOO_VERSION: 10.0 
    DOCKER_COMPOSE_VERSION: 1.17.0 
    ANSIBLE_VERSION: 2.4.2.0

before_install:
  
  # Make sure everything's up to date.
  - sudo apt-get update -qq

  # Install Docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Deploy Odoo using docker-compose available on Docker Hub.
  - 'sudo docker-compose -f ./tests/docker-compose-$ODOO_VERSION.yml up -d'
  - 'sudo sleep 30'

install:

  # Prepare the environnement
  - sudo pip install odoorpc
  - sudo pip install ansible==$ANSIBLE_VERSION

script:

  # Check the role/playbook's syntax
  - 'sudo ansible-playbook tests/test.yml --syntax-check'

  # Run the role/playbook with ansible-playbook
  - 'sudo ansible-playbook tests/test.yml -vvvv --tags change_super_admin_password'
  - 'sudo ansible-playbook tests/test.yml -vvvv --tags database_create'
  - 'sudo ansible-playbook tests/test.yml -vvvv --tags database_backup'
  - 'sudo ansible-playbook tests/test.yml -vvvv --tags database_delete'
  - 'sudo ansible-playbook tests/test.yml -vvvv --tags database_restore'
