---
  - name: Create temporary directory to save the script
    tempfile:
      prefix: odoo-bootstrap-scripts
      state: directory
    register: temp_dir

  - name: Copy Restore Odoo Database Script
    template:
      src: restore_database.py.j2
      dest: "{{ temp_dir.path }}/{{ restore_database_script_dest }}"
      owner: '{{ tablet_user }}'
      group: '{{ tablet_user }}'
      mode: 0733

  - name: Copy Restore Odoo file ZIP 
    copy:
      src: "{{ odoo_database_restore_file }}"
      dest: "/tmp/{{ restore_database_file_dest }}"
      owner: '{{ tablet_user }}'
      group: '{{ tablet_user }}'
      mode: 0733

  - name: check if script file exist
    stat:
      path: "{{ temp_dir.path }}/{{ restore_database_script_dest }}"
    register: stat_result

  - name: Restore Odoo Database using generated script
    command: "python {{ temp_dir.path }}/{{ restore_database_script_dest }}"
    when: stat_result.stat.exists == True

  - name: delete temporary files
    file:
      state: absent
      path: "{{ temp_dir.path }}"

  - name: delete temporary file - Database ZIP file
    file:
      state: absent
      path: "/tmp/{{ restore_database_file_dest }}"
